<div class="commentDeleteSub boxes">
    <form name="commentDeleteSub" action="" method="POST" enctype="multipart/form-data">
        <div id="info" class="info_text">
            <h3>Do you want to delete this comment?</h3>
        </div>
        <div id="delete_submit"><input id="submit_div" type="button" onclick="deleteSubComment(<?php echo (int)$_GET['id']; ?>);" value="delete" /></div>
        <div id="cancel"><input id="no_div" type="button" onclick="tb_remove();" value="no" /></div>
    </form>
</div>