<div class="eventDelete boxes">
    <form name="eventDelete" action="" method="POST" enctype="multipart/form-data">
        <div id="info" class="info_text">
            <h3>Do you want to delete this event?</h3>
        </div>
        <div id="delete_submit"><input id="submit_div" type="button" onclick="deleteEvent(<?php echo $this->id; ?>);" value="Yes" id="delete" /></div>
        <div id="cancel"><input id="no_div" type="button" onclick="tb_remove();" value="No" id="cancel" /></div>
    </form>
</div>