<div class="login">
    <form name="login" action="index" method="POST" enctype="multipart/form-data">
        <div id="login_input">
            <div id="email_input"><input id="login_email" type="text" name="loginEmail" onblur="enableSystemText('login_email');" onfocus="deleteSystemText('login_email');" size="24" value="<?php echo $this->email; ?>" /></div>
            <div id="password_input"><input id="password" type="password" name="loginPassword" size="16" value="" /></div>
        </div>
        <div id="login_submit"><input id="submit_input" type="submit" onclick="return checkLoginInput();" value="login" name="login" /></div>        
    </form>
</div>