<div class="password boxes">
    <div id="new_password_info">
        <p>enter your login email below, and we will send you an email with a new password.</p>
    </div>
    <form name="password" action="" method="POST" enctype="multipart/form-data">
        <div id="new_passord"><input id="email" type="text" name="email" value="" size="33" /></div>
        <div id="new_password_submit"><input id="submit_div" type="button" onclick="return checkNewPasswordInput();" value="do it" name="newPassword" /></div>
        <div id="cancel"><input id="no_div" type="button" onclick="tb_remove();" value="no" id="cancel" /></div>
    </form>
</div>