<div class="privatemsgDelete boxes">
    <form name="privatemsgDelete" action="" method="POST" enctype="multipart/form-data">
        <div id="info" class="info_text">
            <h3>Do you want to delete this message?</h3>
        </div>
        <?php if(isset($_GET['pid'])) { ?>
            <div id="delete_submit"><input id="submit_div" type="button" onclick="deletePrivatemsgGet(<?php echo (int)$_GET['pid']; ?>);" value="delete" /></div>
        <?php } elseif(isset($_GET['psid'])) { ?>
            <div id="delete_submit"><input id="submit_div" type="button" onclick="deletePrivatemsgSended(<?php echo (int)$_GET['psid']; ?>);" value="delete" /></div>
        <?php } ?>
        <div id="cancel"><input id="no_div" type="button" onclick="tb_remove();" value="no" /></div>
    </form>
</div>